### ISSUE TITLE
multiple values are reported invalid but are ok on actual build

### ISSUE THREAD

**Issue by raphaelstolt** [travis-ci/travis-yaml#100]
When validating this [.travis.yml](https://github.com/beberlei/assert/blob/dbf9cc813eeb533b9faa2195a185e8abd60b0419/.travis.yml) against Travis WebLint I get the following lint error message:
```text
in matrix.include.env section: does not support multiple values, dropping LINT=true
```

Running [it](https://travis-ci.org/beberlei/assert/jobs/166812367) on Travis CI doesn't drop the LINT environment variable.

Linting should be in sync with the acual build behaviour. 

Also the misleading lint error message might have people refactoring their Travis CI configuration in a readability decreasing way.
```yml
# fails validation, good readability 
matrix:
  include:
    - php: 7.0
      env:
      - DISABLE_XDEBUG=true
      - LINT=true
```
vs
```yml
# passes validation, decreased readability 
matrix:
  include:
    - php: 7.0
      env: DISABLE_XDEBUG=true LINT=true
```
