### ISSUE TITLE
Container Based Infrastructure

### ISSUE THREAD

**Issue by szepeviktor** [travis-ci/travis-yaml#102]
Travis docs say https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Container-Based-Infrastructure
```yaml
sudo: false
language: php
addons:
  apt:
    packages:
    - cmake
    - time
```
I've added sudo and language.

The linter says
```
    value for addons section is empty, dropping
    in addons section: unexpected key apt, dropping
```
Please advise.
