### ISSUE TITLE
services in matrix.include not recognized as correct.

### ISSUE THREAD

**Issue by LebedevRI** [travis-ci/travis-yaml#108]
```
sudo: required
services:
  - docker
env:
  matrix:
    CI_TARGET=A
matrix:
  include:
    - env: CI_TARGET=B
      sudo: required
      services:
        - docker
```
sudo is already reported in #66
