### ISSUE TITLE
travis fails to validate syntax when comments are present

### ISSUE THREAD

**Issue by zilinc** [travis-ci/travis-yaml#112]
```
# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
language: c
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    # - $HOME/.cabal/packages

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.3
      compiler: ": #GHC 7.10.3"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1
      compiler: ": #GHC 8.0.1"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      compiler: ": #GHC 8.0.2"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}

before_install:
 - unset CC
 - export ALEXVER=3.1.7
 - export HAPPYVER=1.19.5
 - export REPO=$(pwd)
 - export SANDBOX=".cabal-sandbox"

script:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"

 - if diff -u $HOME/.cabsnap/installplan.txt installplan.txt;
   then
     echo "cabal build-cache HIT";
     # OFFENDING COMMENT
   else
     echo "cabal build-cache MISS";
   fi
```
If the offending comment near the bottom is removed, then it validates.
