### ISSUE TITLE
OCTOKIT_API_ENDPOINT fails validation

### ISSUE THREAD

**Issue by aaronmcohen** [travis-ci/travis-yaml#113]
The instructions from https://docs.travis-ci.com/user/deployment/releases/ includes a code snippet which fails to validate:

```yaml
env:
  global:
    - OCTOKIT_API_ENDPOINT: "GITHUB ENTERPRISE API ENDPOINT"
```
results with the following warnings:
- value for env section is empty, dropping
- in env section: value for global section is empty, dropping
- in env.global section: unexpected pair

**Comment by BanzaiMan** [comment]
Ooops. The documentation is wrong. It should be:

```yaml
env:
  global:
    - OCTOKIT_API_ENDPOINT="GITHUB ENTERPRISE API ENDPOINT"
```

I'll fix the documentation shortly.
