### ISSUE TITLE
common rust configuration features are not supported

### ISSUE THREAD

**Issue by dbaron** [travis-ci/travis-yaml#114]
The configuration recommended by both [Travis's own documentation](https://docs.travis-ci.com/user/languages/rust/) and by the [rust documentation](https://doc.rust-lang.org/book/release-channels.html):

```yaml
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
```

is rejected by both `travis lint` and by the [Travis WebLint](http://lint.travis-ci.org/), which I believe are both based on this code.

Another common piece of rust configuration (recommended by [this blog post on running rustfmt in Travis CI](http://johannh.me/blog/rustfmt-ci.html)):

```yaml
cache: cargo
```

is also rejected.  `travis lint` reports:

```
Warnings for .travis.yml:
[x] in matrix.allow_failures section: unexpected key rust, dropping
[x] unexpected key rust, dropping
[x] value for cache section is empty, dropping
[x] in cache section: unexpected key cargo, dropping
```
