### ISSUE TITLE
`dist:` in `matrix` section marked as "dropped" by linter, works 👌  in build

### ISSUE THREAD

**Issue by ntwb** [travis-ci/travis-yaml#118]
The following fails at https://lint.travis-ci.org/ and returns an error: `in matrix.include section: unexpected key dist, dropping`. The build passes though and the PHP 5.2 & 5.3 jobs do use Precise as the distro in the build.

```yaml
sudo: false
language: php
dist: trusty
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
env:
  - WP_VERSION=master
  - WP_VERSION=4.7

# Build matrix options
matrix:
  include:
    - php: 5.3
      env: WP_VERSION=4.7
      dist: precise
    - php: 5.2
      env: WP_VERSION=master
      dist: precise
```
