### ISSUE TITLE
Unexpecting keys `apt`, `elapsed_time` and `on_pull_requests`

### ISSUE THREAD

**Issue by cas--** [travis-ci/travis-yaml#121]
Although below config snippet works on Travis, running it through the linter results in:
```
    in notifications.slack.template section: unknown template variable elapsed_time
    in notifications.slack section: unexpected key on_pull_requests, dropping
    value for addons section is empty, dropping
    in addons section: unexpected key apt, dropping
```

```
language: python

addons:
  apt:
    packages:
    - aspell

notifications:
  slack:
    rooms:
      - secure: abc
    on_pull_requests: false
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
```

**Comment by ntwb** [comment]
I was about to report the _addons_ issue, I'll piggy back this onto this issue here:

The docs at https://docs.travis-ci.com/user/installing-dependencies/#Adding-APT-Packages state:
```yaml
addons:
  apt:
    packages:
    - cmake
    - time
```

So the linter or the docs should be updated
