### ISSUE TITLE
Parser false negative

### ISSUE THREAD

**Issue by mvrozanti** [travis-ci/travis-yaml#131]
The following `.travis.yml` is accepted and works as expected on travis-ci.com and yet the command `travis lint .travis.yml` prints out a ton of warnings:

```
language: cpp

compiler:
  - gcc

matrix:

  allow_failures:
    - os: osx
    - os: windows

  include:

    - os: linux
      env: REGISTER_WIDTH=auto

    - os: osx
      env: REGISTER_WIDTH=auto

    - os: windows
      env: REGISTER_WIDTH=auto

    - os: linux
      env: REGISTER_WIDTH=128

    - os: osx
      env: REGISTER_WIDTH=128

    - os: windows
      env: REGISTER_WIDTH=128

    - os: linux
      env: REGISTER_WIDTH=256
      sudo: yes
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install: 
        - sudo apt-get install -qq g++-7
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script:
    - mkdir build 
    - cd build
    - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
    - make -j 2
```

Warnings:

```
Warnings for /home/nexor/mackenzie/tcc1/PyDistance/.travis.yml:
[x] in matrix.include section: unexpected key sudo, dropping
[x] in matrix.include section: unexpected key dist, dropping
[x] in matrix.include section: unexpected key before_install, dropping
[x] in matrix.include section: unexpected key install, dropping
[x] in matrix.include.os section: illegal value windows, defaulting to linux
[x] in matrix.allow_failures.os section: illegal value windows, defaulting to linux
```

I appreciate the `illegal value windows` message but hey whatever floats your boat.
