### ISSUE TITLE
Warn if the same key appears twice

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-yaml#25]
``` yaml
addons:
  postgresql: "9.3"

⋮
# stuff

addons:
  code_climate:
    api_token: "foobar"
```

Results in only one addon being acknowledged. We should warn about this.
