### ISSUE TITLE
Add support for `on_failure` and `on_success` in `notifications`

### ISSUE THREAD

**Issue by Zarthus** [travis-ci/travis-yaml#43]
Hello,

Currently, there is no support for `on_failure` and `on_success` in the notifications for a travis yaml file.

A simple YAML file:

``` yaml
language: php
php: 5.5

notifications:
  email: true
  on_failure: always
  on_success: change
```

returns

```
in notifications section: unexpected key on_failure, dropping
in notifications section: unexpected key on_success, dropping
```

This feature is [documented here](http://docs.travis-ci.com/user/notifications/#Email-notifications) and works just fine. travis-yaml just doesn't appear to support it yet.

Thanks!
- Zarthus.
