### ISSUE TITLE
notifications.webhooks section: dropping on_start section: illegal value true

### ISSUE THREAD

**Issue by serious6** [travis-ci/travis-yaml#47]
Taken the folowing configuration from [notifications/#Webhook-notification](http://docs.travis-ci.com/user/notifications/#Webhook-notification)

``` yml
notifications:
  webhooks:
    urls:
      - http://some.hook.com/foo
    on_success: always # default: always
    on_failure: always # default: always
    on_start: true # [true / false] default: false
```

for `on_start` the values are indicated to be true or false but both are reported as beeing wrong while [validating the yaml](http://yaml.travis-ci.org/). Is this a validation-bug or is the documentation wrong?
