### ISSUE TITLE
addons -> apt parsing returning errors

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-yaml#58]
Taking an example from http://docs.travis-ci.com/user/apt/
<pre>
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
</pre>

Enter into http://lint.travis-ci.org/

result:
<pre>
value for addons section is empty, dropping
..
in addons section: unexpected key apt, dropping
<pre>

**Comment by mauritsvanrees** [comment]
I see the same. I am trying to follow the directions from http://docs.travis-ci.com/user/migrating-from-legacy/
That means a .travis.yml like this:

```
sudo: false
language: python
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - time
```
Enter this at http://lint.travis-ci.org and you get the same errors as above:
- value for addons section is empty, dropping
- in addons section: unexpected key apt, dropping

So I now have no idea how to migrate from legacy to container based infrastructure if I need extra apt packages.

**Comment by moylop260** [comment]
I have same issue

**Comment by mauritsvanrees** [comment]
I had this problem too. But note that Travis itself may run just fine even when the linter at http://lint.travis-ci.org/ fails. See the issue linked just above this comment. In my case I failed to notice that I was changing this:

```
before_install:
  - sudo apt-get install git-svn
# Several lines of comments
  - pip install stuff
```

into this:

```
addons:
  apt:
    packages:
    - git-svn
# Several lines of comments
  - pip install stuff
```

I had removed the `before_install` section because I did not notice it did more than just apt-get install stuff. It should have been this:

```
addons:
  apt:
    packages:
    - git-svn
before_install:
# Several lines of comments
  - pip install stuff
```

So: double check that there are no problems in the lines after the addons.
And: yes, the linter still needs to be fixed.
