### ISSUE TITLE
unexpected key scala, dropping

### ISSUE THREAD

**Issue by kopiczko** [travis-ci/travis-yaml#60]
[Online lint](http://lint.travis-ci.org/) shows _unexpected key scala, dropping_ with following config:

```yaml
language: scala
jdk: oraclejdk7
scala:
  - 2.11.6
```
