### ISSUE TITLE
Multiple nested keys with the same name results in the last one winning?

### ISSUE THREAD

**Issue by solarce** [travis-ci/travis-yaml#64]
In troubleshooting https://secure.helpscout.net/conversation/98485511/17130/ I ended up with a case where it seems that when you specific multiple nested keys with the same names in `.travis.yml`, the last one wins.

E.g. 

```
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
addons:
  apt:
    packages:
    - libyajl-dev
    - libxml2-dev
    - gcc-4.8
    - g++-4.8
#   - libxqilla
addons:
  apt:
    sources:
    - deadsnakes
```

Ends up being processed as just as the following, during a build:

```
addons:
  apt:
    sources:
    - deadsnakes
```

See https://github.com/solarce/pbdagcon/blob/6258d2b324508bf38acf2e938fe77d4807d7d484/.travis.yml#L14-L29 and https://travis-ci.org/solarce/pbdagcon/builds/67409496#L86-L97 for an example of this in action.

Changing the `.travis.yml` to https://github.com/solarce/pbdagcon/blob/master/.travis.yml#L14-L22 results in the desired outcome of the `apt` addon config and the build https://travis-ci.org/solarce/pbdagcon/builds/67410797
