### ISSUE TITLE
sudo in matrix.include not recognized as correct.

### ISSUE THREAD

**Issue by bilderbuchi** [travis-ci/travis-yaml#66]
When putting a snippet like
```
sudo: false
env:
  matrix:
    CI_TARGET=A
matrix:
  include:
    - env: CI_TARGET=B
      sudo: true
```
I get "in matrix.include section: unexpected key sudo, dropping", but this works on Travis.

**Comment by cirocosta** [comment]
can't reproduce this; here this works:

```yaml
sudo: false
language: go

go:
  - master

env:
  - TEST_SUITE="unit"

matrix:
  include:
    - env: "TEST_SUITE=integration"
      sudo: true
```
