### ISSUE TITLE
.travis.yml file fails Lint but passes build. please tell me what is wrong!

### ISSUE THREAD

**Issue by nelsonic** [travis-ci/travis-yaml#77]
Hi Travis Team/Community! 
Can someone tell me what is wrong with this travis.yml file:
```yml
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - 0.12
services:
  - redis-server
before_install:
  - pip install --user codecov
after_success:
  - codecov
```
It ***fails*** in the Travis WebLint: http://lint.travis-ci.org/

But passes travis build:  https://travis-ci.org/dwyl/hapi-socketio-redis-chat-example/builds/89449194

The reason I'm asking is because I want to use this `.travis.yml` as the basis for another project, but *given* that it fails Lint I want to know what is wrong before proceeding...
