### ISSUE TITLE
colon syntax error fase detected?

### ISSUE THREAD

**Issue by davidak** [travis-ci/travis-yaml#81]
```
before_install:
  - printf "CPU:"
  - grep model\ name /proc/cpuinfo | head -1 | cut -f2 -d:
  - printf "CPU Cores: "
  - grep -c processor /proc/cpuinfo
```
>syntax error: (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 4 column 25

I think this is not an error since it is quoted.

**Comment by BanzaiMan** [comment]
You have an unquoted dangling `:` in `grep model\ name /proc/cpuinfo | head -1 | cut -f2 -d:`.

**Comment by BanzaiMan** [comment]
Actually, the error is on line 4… There is a trailing space after `:` that's fooling the parser. Try quoting the entire string:

```yaml
before_install:
  - printf "CPU:"
  - grep model\ name /proc/cpuinfo | head -1 | cut -f2 -d:
  - "printf CPU Cores: "
  - grep -c processor /proc/cpuinfo
```
