### ISSUE TITLE
matrix.include.addons - says addons are dropped but they work

### ISSUE THREAD

**Issue by Adam-Goldman7** [travis-ci/travis-yaml#88]
passing this to the linter:
```
matrix:
  include:
    - env: SCRIPT=lint
    - env: SCRIPT=testOnce
    - env: SCRIPT=nightwatchCI
      addons:
        sauce_connect:
          username: ""
          access_key: ""
```

will give this warning:
`in matrix.include section: unexpected key addons, dropping`

altho in the build it does trigger sauce_connect only on nightwatchCI script

am I doing something wrong here?
