### ISSUE TITLE
【BUG】the setting variable not work

### ISSUE THREAD

**Issue by yozman** [travis-ci/travis-yaml#92]
heyguys,

when I try to use webhook as string it works like this:
```yaml
notifications:
  webhooks:
    urls:
      - https://hooks.pubu.im/services/whatthefly
    on_start: always
```

but when I try to replace the token `whatthefly`,
use `Environment Variables` like this:
```yaml
notifications:
  webhooks:
    urls:
      - https://hooks.pubu.im/services/$TOKEN
    on_start: always
```
it doesn't work, I'm sure I have the right setting.

could you tell me what should I do to let it work?
