### ISSUE TITLE
array values in `language:` and `dist:` keys are reported as valid

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/travis-yaml#94]
`language:` and `dist:` keys should be listed as single values rather than in an array

This works:

```yaml
language: cpp
dist: trusty
````

This fails due to an error parsing the `.travis.yml` file

```yaml
language: 
  - cpp

dist: 
  - trusty

```

but both are reported as valid by lint 

cc/ @bblacey
