### ISSUE TITLE
Site suggest failure with no failure 

### ISSUE THREAD

**Issue by DonRichards** [travis-ci/travis-yaml#98]
This passes on Travis but fails on lint.travis-ci.org

```
sudo: required
dist: trusty
language: bash
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
before_install:
- echo "Before Install scripts Start"
install:
- echo "Install scripts Starting."
script:
- echo "shell commands Starting"
- bash -c 'shopt -s globstar; shellcheck **/*.{sh,bash}'
after_success:
- echo "PASSED!"
after_failure:
- echo "FAILURE IS ALWAYS AN OPTION"
after_script:
- echo "more shell commands here"
notifications:
```
